### ISSUE TITLE
the intrinsics of the RGB camera in 7Scenes dataset 

### ISSUE THREAD

**Issue by Guan2014** [sfu-gruvi-3dv/sanet_relocal_demo#2]
Thank you for sharing your code. As is shown in the website https://www.microsoft.com/en-us/research/project/rgb-d-dataset-7-scenes/, only the  intrinsics for the depth camera is available. Could you please tell me how you get the intrinsics of the RGB camera in 7Scenes dataset?

**Comment by corsy** [comment]
The author of Learning less is more share RGB intrinsic parameter: https://github.com/vislearn/LessMore, check his data package: https://cloudstore.zih.tu-dresden.de/index.php/s/5hHv4gywLFI9K07.

**Comment by Guan2014** [comment]
@corsy Thanks for your answer. I saw the data package, and it just give the focal length. I find that the code of Learning less use half the width and half the height of the image as the coordination of principal point, but you use 324, 244.  How do you get these numbers?

**Comment by corsy** [comment]
> @corsy Thanks for your answer. I saw the data package, and it just give the focal length. I find that the code of Learning less use half the width and half the height of the image as the coordination of principal point, but you use 324, 244. How do you get these numbers?

Are you refer to `relocal_data/seven_scene/seven_scene_dataset.py` ? In test, we use `relocal_data/seven_scene/seven_scene_manual_dataset.py` instead, cx,cy are fixed to 320, 240 in line 29, 30.

**Comment by Guan2014** [comment]
Yes, I referred to relocal_data/seven_scene/seven_scene_dataset.py. Thanks for your help.
