### ISSUE TITLE
copy-paste error test_seq -> train_seq

### ISSUE THREAD

**Issue by amonszpart** [sfu-gruvi-3dv/sanet_relocal_demo#7]
https://github.com/sfu-gruvi-3dv/sanet_relocal_demo/blob/2f5b4edc7568104023de0068d767019c10b03231/seq_data/seven_scenes/scenes2seq.py#L118-L119

L119 should say `train_seq`: 
```python
json_path = os.path.join(seq_dir, 'seq-%02d' % train_seq, 'seq.json')
```

**Comment by corsy** [comment]
Thank you for finding this issue. It should work now, I checked the output data with my raw data that was generated from correct version.
