### ISSUE TITLE
[ 33%] Building CXX object CMakeFiles/lm_pnp.dir/lm_pnp_interface.cpp.o

### ISSUE THREAD

**Issue by fddehnavi** [sfu-gruvi-3dv/sanet_relocal_demo#9]
Hello 
I do make all and this error occurred. what should i do?
would you please link the person who wrote the code?

[ 33%] Building CXX object CMakeFiles/lm_pnp.dir/lm_pnp_interface.cpp.o
In file included from /home/libs/utils/lm_pnp/lm_pnp_interface.cpp:10:0:
/home /libs/utils/lm_pnp/cnn.h: In function 'cv::Mat_<float> getDiffMap(const cv_trans_t&, const img_coord_t&, const cv::Mat_<cv::Point_<int> >&, const cv::Mat&)':
/home/libs/utils/lm_pnp/cnn.h:156:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(unsigned x = 0; x < sampling.cols; x++)
                         ~~^~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:157:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(unsigned y = 0; y < sampling.rows; y++)
                         ~~^~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h: In function 'std::vector<double, std::allocator<double> > getHypScores(std::vector<cv::Mat_<float> >&, double)':
/home/libs/utils/lm_pnp/cnn.h:225:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < diffMaps.size(); i++)
                    ~~^~~~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:228:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(unsigned x = 0; x < diffMaps[i].cols; x++)
                             ~~^~~~~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:229:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(unsigned y = 0; y < diffMaps[i].rows; y++)
                                 ~~^~~~~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h: In function 'void processImageModified(int, const cv::Mat&, float, int, double&, double&, bool&, std::vector<std::pair<cv::Mat, cv::Mat> >&, std::vector<double, std::allocator<double> >&, const img_coord_t&, const cv::Mat_<cv::Point_<int> >&, std::vector<std::vector<cv::Point_<int> > >&, std::vector<double, std::allocator<double> >&, std::vector<cv::Mat_<int> >&, double&, double&, int&, bool, bool)':
/home/libs/utils/lm_pnp/cnn.h:374:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(!training && hypIdx != h)
                         ~~~~~~~^~~~
/home/libs/utils/lm_pnp/cnn.h:380:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(unsigned rStep = 0; rStep < refSteps; rStep++)
                                 ~~~~~~^~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:387:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(unsigned x = 0; x < localDiffMap.cols; x++)
                                 ~~^~~~~~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:388:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(unsigned y = 0; y < localDiffMap.rows; y++)
                                     ~~^~~~~~~~~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:270:17: warning: unused parameter 'expectedLoss' [-Wunused-parameter]
         double& expectedLoss,
                 ^~~~~~~~~~~~
/home/libs/utils/lm_pnp/cnn.h:272:15: warning: unused parameter 'correct' [-Wunused-parameter]
         bool& correct,
               ^~~~~~~
/home/libs/utils/lm_pnp/cnn.h:278:30: warning: unused parameter 'losses' [-Wunused-parameter]
         std::vector<double>& losses,
                              ^~~~~~
/home/libs/utils/lm_pnp/cnn.h:280:17: warning: unused parameter 'tErr' [-Wunused-parameter]
         double& tErr,
                 ^~~~
/home/libs/utils/lm_pnp/cnn.h:281:17: warning: unused parameter 'rotErr' [-Wunused-parameter]
         double& rotErr,
                 ^~~~~~
/home/libs/utils/lm_pnp/cnn.h:283:45: warning: unused parameter 'verbose' [-Wunused-parameter]
         bool training = false, bool verbose=false)
                                             ^~~~~
/home/libs/utils/lm_pnp/lm_pnp_interface.cpp: In function 'pybind11::tuple compute_lm_pnp(pybind11::array_t<float>, pybind11::array_t<float>, pybind11::array_t<float>, float, int, int, bool)':
/home/libs/utils/lm_pnp/lm_pnp_interface.cpp:311:19: error: 'class pybind11::array_t<float>' has no member named 'resize'; did you mean 'size'?
     pred_pose_vec.resize({6});
                   ^~~~~~
                   size
/home/libs/utils/lm_pnp/lm_pnp_interface.cpp:312:16: error: 'class pybind11::array_t<int>' has no member named 'resize'; did you mean 'size'?
     inlier_map.resize({H, W});
                ^~~~~~
                size
/home/libs/utils/lm_pnp/lm_pnp_interface.cpp: At global scope:
/home/libs/utils/lm_pnp/lm_pnp_interface.cpp:325:16: error: expected constructor, destructor, or type conversion before '(' token
 PYBIND11_MODULE(lm_pnp, m){
                ^
CMakeFiles/lm_pnp.dir/build.make:62: recipe for target 'CMakeFiles/lm_pnp.dir/lm_pnp_interface.cpp.o' failed
make[2]: *** [CMakeFiles/lm_pnp.dir/lm_pnp_interface.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lm_pnp.dir/all' failed
make[1]: *** [CMakeFiles/lm_pnp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by corsy** [comment]
which pybind11 version are you use? can you pass the unit test test_numpy_array in pybind11?

**Comment by fddehnavi** [comment]
it solved. I installed pybind11 2.4.3 .
Thank you.
